name: CI build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        postgres-version: [ 10, 11, 12, 13, 14 ]

    steps:
    - uses: actions/checkout@v2

    - name: Install locales on runner
      run: sudo apt-get install -y locales-all

    - uses: actions/setup-java@v2
      id: build_java
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: Build
      run: |
          ./mvn -B -Dpg-embedded.postgres-version=${{ matrix.postgres-version }} clean install
