---
name: CI build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17, 21, 24 ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Install locales on runner
        run: |
          sudo apt-get update
          sudo apt-get install -y locales-all

      - uses: actions/setup-java@v4
        name: setup build jdk
        id: build_jdk
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: build code
        id: install_fast
        env:
          MAVEN_ARGS: "-B -ff"
        run: |
          ./mvnw --version
          make install-fast

      - uses: actions/setup-java@v4
        name: setup test jdk
        id: test_jdk
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin

      - name: run tests
        id: run_tests
        env:
          MAVEN_ARGS: "-B -ff"
        run: |
          ./mvnw --version
          make run-tests

  db:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres-version: [ 17, 16, 15, 14, 13 ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Install locales on runner
        run: |
          sudo apt-get update
          sudo apt-get install -y locales-all

      - uses: actions/setup-java@v4
        name: setup build jdk
        id: build_jdk
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: build code
        id: install_fast
        env:
          MAVEN_ARGS: "-B -ff"
        run: |
          ./mvnw --version
          make install-fast

      - name: run tests
        id: run_tests
        env:
          MAVEN_ARGS: "-B -ff -Dpg-embedded.postgres-version=${{ matrix.postgres-version }}"
        run: |
          ./mvnw --version
          make run-tests
