name: CI build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-java-version: [ 11, 17 ]
        test-java-version: [ 11, 17, 20 ]
        postgres-version: [ 9.6, 10, 11, 12, 13, 14, 15 ]

    steps:
    - uses: actions/checkout@v3

    - name: Install locales on runner
      run: sudo apt-get install -y locales-all

    - uses: actions/setup-java@v3
      id: setup_build_jdk
      name: Setup Build JDK
      with:
        java-version: ${{ matrix.build-java-version }}
        distribution: temurin
        cache: maven

    - name: Build
      env:
        MAVEN_CONFIG: "-Pfast -Dbasepom.check.skip-enforcer=false -B -fae"
      run: |
        ./mvnw --version
        make install

    - uses: actions/setup-java@v3
      id: setup_test_jdk
      name: Setup Test JDK
      with:
        java-version: ${{ matrix.test-java-version }}
        distribution: temurin
        cache: maven

    - name: Run unit tests
      env:
        MAVEN_CONFIG: "-B -fae -Dpg-embedded.postgres-version=${{ matrix.postgres-version }}"
      run: |
        ./mvnw --version
        make test
