---
name: CD (Snapshot deployment)

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Install locales on runner
        run: |
          sudo apt-get update
          sudo apt-get install -y locales-all

      - uses: actions/setup-java@v4
        name: setup build jdk
        id: build_jdk
        with:
          java-version: 21
          distribution: temurin
          cache: maven
          server-id: central
          server-username: CENTRAL_REPO_USER
          server-password: CENTRAL_REPO_PASSWORD

      - name: deploy code
        env:
          CENTRAL_REPO_USER: ${{ secrets.CENTRAL_REPO_USER }}
          CENTRAL_REPO_PASSWORD: ${{ secrets.CENTRAL_REPO_PASSWORD }}
          MAVEN_ARGS: "-B -ff"
        run: |
          make deploy

  site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Install locales on runner
        run: |
          sudo apt-get update
          sudo apt-get install -y locales-all

      - name: Set git information
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ github.actor }}

      - uses: actions/setup-java@v4
        name: setup build jdk
        id: build_jdk
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PG_EMBEDDED_GITHUB_IO_DEPLOY_KEY }}

      - name: deploy documentation
        env:
          MAVEN_ARGS: "-B -ff"
        run: |
          make deploy-site
