name: CD from master pushes

on:
  push:
    branches:
    - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install locales on runner
      run: sudo apt-get install -y locales-all

    - uses: actions/setup-java@v3
      id: build_java
      with:
        java-version: 17
        distribution: temurin
        cache: maven
        server-id: sonatype-nexus-snapshots
        server-username: NEXUS_REPO_USER
        server-password: NEXUS_REPO_PASSWORD

    - name: Build
      run: |
          ./mvnw -B clean deploy
      env:
        NEXUS_REPO_USER: ${{ secrets.NEXUS_REPO_USER }}
        NEXUS_REPO_PASSWORD: ${{ secrets.NEXUS_REPO_PASSWORD }}

  site:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install locales on runner
      run: sudo apt-get install -y locales-all

    - name: Set git information
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com

    - uses: actions/setup-java@v3
      id: build_java
      with:
        java-version: 17
        distribution: temurin
        cache: maven
        server-id: github
        server-username: SITE_DEPLOY_USER
        server-password: SITE_DEPLOY_TOKEN

    - name: Deploy site
      # run install b/c https://issues.apache.org/jira/browse/MJAVADOC-701
      run: |
          ./mvnw -B clean install site-deploy
      env:
        SITE_DEPLOY_USER: ${{ secrets.SITE_DEPLOY_USER }}
        SITE_DEPLOY_TOKEN: ${{ secrets.SITE_DEPLOY_TOKEN  }}
